### ISSUE TITLE
运行mu报错

### ISSUE THREAD

**Issue by echoowall** [orvice/shadowsocks-go#12]
DEBU[0000] debug on  
INFO[0000] PONG  
INFO[0000] 0  
INFO[0000] 0  
INFO[0000] 0  
INFO[0000] sync finish...  
INFO[0000] 0  
DEBU[0000] []  
INFO[0000] check finish... 
请问这是怎么回事

**Comment by orvice** [comment]
没有取到用户数据，发下配置

**Comment by echoowall** [comment]
## 配置说明  https://github.com/orvice/shadowsocks-go/wiki/Config

[base]
N 1
ip 0.0.0.0
client webapi
checktime  60
synctime   60

[webapi]
url http://lys.miaoss.win/mu
key ztone
node_id 1

[mysql]
host  127.0.0.1:3306
user user
pass pass
db   db
table table

[redis]
host localhost:6379

# if no passwd set,comment this line

#pass ""
db 1

**Comment by echoowall** [comment]
//  ss-panel v3 配置
//
// !!! 修改此key为随机字符串确保网站安全 !!!
key = 'ztone'
debug =  'false'  //  正式环境请确保为false
appName = 'lys'             //站点名称
baseUrl = 'http://lys.miaoss.win'            // 站点地址
timeZone = 'PRC'        // RPC 天朝时间  UTC 格林时间
pwdMethod = 'sha256'       // 密码加密   可选 md5,sha256
salt = 'ztone'               // 密码加密用，从旧版升级请留空
theme    = 'default'   // 主题
authDriver = 'redis'   // 登录验证存储方式,推荐使用Redis   可选: cookie,redis
sessionDriver = 'redis'
cacheDriver   = 'redis'

**Comment by echoowall** [comment]
ERRO[0000] no section for key: ﻿## at 1  
现在报这个了。sspanel和shadowsocks-go在同一台vps下。

**Comment by orvice** [comment]
// mu key 用于校验ss-go mu的请求
muKey = 'ztone'

.env加这个。

ps 你的key已经发出来了，自己修改下。否则有危险

**Comment by echoowall** [comment]
我更新了sspanel，并且更新了key字段，现在还是报ERRO[0000] no section for key: ﻿## at 1 ···········

**Comment by orvice** [comment]
http://lys.miaoss.win/mu/users?key=ztone
访问这个有数据？
key自己换下

**Comment by echoowall** [comment]
有数据的

**Comment by echoowall** [comment]
我重新弄了一遍config.conf，现在报这个ERRO[0000] boot redis fail: ERR Client sent AUTH, but no password is set 
······

**Comment by echoowall** [comment]
现在可以了，谢谢，应该是我的文本的问题
