### ISSUE TITLE
升级到最新版本后，运行./mu报错

### ISSUE THREAD

**Issue by Acris** [orvice/shadowsocks-go#15]
sync finish...start logging online count 
invalid character '<' looking for beginning of value

**Comment by orvice** [comment]
这个是记录在线人数

需要新的ss-panel https://github.com/orvice/ss-panel/tree/dev

导入新表 ss_node_online_log.sql

**Comment by Acris** [comment]
好的，已解决。
另外问一下，除了使用screen、supervisor等工具以外，shadowsocks-go mu自己是否支持后台运行？

**Comment by orvice** [comment]
用supervisor吧，go的deamon包我还没用过
