### ISSUE TITLE
节点在线人数一直是0呢

### ISSUE THREAD

**Issue by glzjin** [orvice/shadowsocks-go#17]
迫不及待的升级测试了下。。。然而发现记录到的都是0。

**Comment by orvice** [comment]
昨天有个bug改太晚了。。
忘记push了
在最新dev分支
https://github.com/orvice/shadowsocks-go/tree/dev

**Comment by glzjin** [comment]
谢谢，马上更新～
2016年3月6日 上午11:38，orvice notifications@github.com写道：昨天有个bug改太晚了。。
忘记push了
在最新dev分支
https://github.com/orvice/shadowsocks-go/tree/dev

**Comment by glzjin** [comment]
然而，更新之后，还是0= =看代码的话 貌似在不更改Redis数据库的情况下还得等一个小时？

**Comment by orvice** [comment]
不用等啊
更新重启会开始记录五分钟在线人数

**Comment by glzjin** [comment]
好吧，谢谢，辛苦了。。。。不过目前看的话，还都是0。。。不过确实是有人在用的。。。我是想原先 Redis 里已有的数据会不会造成影响。。。。
2016年3月6日 下午12:55，orvice notifications@github.com写道：不用等啊

更新重启会开始记录五分钟在线人数

**Comment by orvice** [comment]
redis-cli进去
keys useronline\* 看下有内容不

**Comment by glzjin** [comment]
173) "userinfo:30493"
174) "userinfo:30097"
175) "userinfo:30496"
176) "userflow:30134"
177) "userflow:30054"
178) "userflow:30372"
179) "userflow:30058"
180) "userinfo:30100"
redis 127.0.0.1:6379[3]> keys useronline*
(empty list or set)
redis 127.0.0.1:6379[3]>
2016年3月6日 下午1:26，orvice notifications@github.com写道：redis-cli进去
keys useronline\* 看下有内容不

**Comment by orvice** [comment]
是不是啦错分支了。。
https://github.com/orvice/shadowsocks-go/tree/dev

不是mu

**Comment by glzjin** [comment]
之前 checkout 了 是 dev 编出来的= =
2016年3月6日 下午1:42，orvice notifications@github.com写道：是不是啦错分支了。。
https://github.com/orvice/shadowsocks-go/tree/dev

不是mu

**Comment by glzjin** [comment]
ERRO[0016] ERR wrong number of arguments for 'set' command
ERRO[0016] [port-30000]  Error: request 8.8.8.8:53 cancel
dev 还出现了这个问题。。。
2016年3月6日 下午1:58，glzjin glzjin@zhaojin97.cn写道：之前 checkout 了 是 dev 编出来的= =
2016年3月6日 下午1:42，orvice notifications@github.com写道：是不是啦错分支了。。
https://github.com/orvice/shadowsocks-go/tree/dev

不是mu

**Comment by orvice** [comment]
编译有没有到
$GOPATH/src/github.com/orvice/shadowsocks-go/mu
下编译？
确保此目录在dev分支下

**Comment by glzjin** [comment]
有的 在dev分支下
2016年3月6日 下午2:37，orvice notifications@github.com写道：编译有没有到
$GOPATH/src/github.com/orvice/shadowsocks-go/mu
下编译？
确保此目录在dev分支下

**Comment by orvice** [comment]
试试看我编译的？
https://github.com/orvice/test/blob/master/mu

**Comment by glzjin** [comment]
嗯，测试了，也还是出现了一样的两个问题：
1、在线人数一直为0
2、出现了如下的错误信息，且联网困难，表现为域名解析失败。

> ERRO[0016] ERR wrong number of arguments for 'set' command
> ERRO[0016] [port-30000]  Error: request 8.8.8.8:53 cancel

**Comment by glzjin** [comment]
在使用mu和dev分支编译使用的时候，问题1一直会出现。

在使用dev分支编译时，问题2会出现。

**Comment by glzjin** [comment]
https://github.com/redis/redis-rb/issues/372

找到原因了。。。CentOS6 默认的 Redis 版本太老了。。。谢谢

**Comment by glzjin** [comment]
问题解决，谢谢。
