### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by fsgmhoward** [orvice/shadowsocks-go#18]
提示：

```
INFO[0121] sync finish...start logging online count
ERRO[0121] invalid character '<' looking for beginning of value
```

**Comment by fsgmhoward** [comment]
实际上貌似并不影响使用

**Comment by orvice** [comment]
这个是更新在线人数的时候报错，不影响。

是否是最新dev分支的ss-panel?

**Comment by glzjin** [comment]
API地址是不是做了301/302跳转？

**Comment by orvice** [comment]
没有做

**Comment by orvice** [comment]
@glzjin 你是不是用cloudflare做cdn

**Comment by fsgmhoward** [comment]
@orvice 不是dev分支的，我用的是master分支的ss-panel

**Comment by glzjin** [comment]
并不是，是升级到sspanel 3.0之后就换了个域名，原先就做了个跳转，结果= =就是跟他一模一样的错误，换成不跳转的域名就OK了。
2016年3月8日 上午12:49，orvice notifications@github.com写道：@glzjin 你是不是用cloudflare做cdn

**Comment by orvice** [comment]
@fsgmhoward 目前需要dev分支的ss-panel才可以记录在线人数
@glzjin http跳https？config.conf填写的url是带https？

**Comment by glzjin** [comment]
两个都是https，由https：//a.aaa.com 跳转到https://b.aaa.com。
2016年3月8日 上午9:55，orvice notifications@github.com写道：@fsgmhoward 目前需要dev分支的ss-panel才可以记录在线人数
@glzjin http跳https？config.conf填写的url是带https？

**Comment by orvice** [comment]
@glzjin 做跳转的话post可能会获取不到数据，配置里的url建议直接写 https://b.aaa.com
具体原因我会在看下。

**Comment by glzjin** [comment]
嗯，做跳转之后就是发现在现人数这里有点问题，其他都还好，用跳转之后的地址就都ok了，幸苦了，谢谢。
2016年3月8日 上午10:17，orvice notifications@github.com写道：@glzjin 做跳转的话post可能会获取不到数据，配置里的url建议直接写 https://b.aaa.com
具体原因我会在看下。

**Comment by orvice** [comment]
如果是post，似乎要做307跳转，不然post会变成get
参见
http://blog.sina.com.cn/s/blog_62b832910102v6xi.html

**Comment by glzjin** [comment]
在 2016-03-08 11:01，orvice 写道：

> 如果是post，似乎要做307跳转，不然post会变成get
> 参见
> http://blog.sina.com.cn/s/blog_62b832910102v6xi.html 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

好的，谢谢。 

## Links:

[1]
https://github.com/orvice/shadowsocks-go/issues/18#issuecomment-193578126
