### ISSUE TITLE
Vultr VPS Ubuntu 14.04 64 bit执行go get报错

### ISSUE THREAD

**Issue by Acris** [orvice/shadowsocks-go#20]
go version：go1.6 linux/amd64

进入mu目录后执行go get，会提示以下错误：
# github.com/orvice/shadowsocks-go/mu/mysql

mysql/mysql_boot.go:24: cannot use &db (type **gorm.DB) as type *gorm.DB in argument to c.SetDb

master分支和dev分支都会报错。

昨天在IDCF的VPS上，同样的系统和Go版本，go get的时候没有问题。

**Comment by Acris** [comment]
刚刚尝试换go 1.5.3 仍然报同样的错误..

**Comment by orvice** [comment]
gorm 更新类型变了导致
https://github.com/jinzhu/gorm/pull/794/files

**Comment by Acris** [comment]
嗯嗯，刚刚看你已经修复了，感谢。
