### ISSUE TITLE
webapi连接ssl的问题及mysql的问题, 求大大出手

### ISSUE THREAD

**Issue by jerryh80** [orvice/shadowsocks-go#25]
用webapi连接, 但是我的网站地址是启用了ssl的, 并且配置http强制跳转https, 但是我的是个人未认证证书, 运行mu出现如下错误:
ERRO[0000] Get User ErrorGet https://45.32.**.**/users?key=***FFFGYYdrrt89: x509: certificate signed by unknown authority 

另外尝试配置mysql, 配置如下:

[mysql]
host  45.32.**.**:3306
user ss
pass ******
db   shadowsocks
table table

table这里不知道怎么填, 是填user这个表么?

然后运行出现以下错误, go版本为1.6: 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x401118]

goroutine 1 [running]:
panic(0x982c20, 0xc82000e0f0)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
main.boot()
    /root/workstation/go/src/github.com/orvice/shadowsocks-go/mu/boot.go:31 +0x118
main.main()
    /root/workstation/go/src/github.com/orvice/shadowsocks-go/mu/main.go:31 +0x28f

**Comment by orvice** [comment]
certificate signed by unknown authority

证书错误

**Comment by jerryh80** [comment]
嗯,是的, 证书肯定有问题啊, 因为我只是启用了个人认证的证书而已(self-signed), 并没有花钱去开通三方认证的, 能有个像 wget一样 --no-check-certificate 这样的参数直接跳过个人认证证书么? 或者比如git的 http.sslVerify false

**Comment by orvice** [comment]
不要用https就好了啊
现在暂时不支持忽略证书验证

**Comment by VishKozus** [comment]
可以从证书侧解决。用免费签名的证书，比如[ let's encrypt](https://github.com/letsencrypt/letsencrypt)
