### ISSUE TITLE
怎样解决启动./mu错误?

### ISSUE THREAD

**Issue by zhako022** [orvice/shadowsocks-go#26]
安装ss go mu后 ./mu启动出现错误
ERRO[0000] error listening port 1333: listen tcp :1333: bind: address already in use
请问怎样解决?

**Comment by orvice** [comment]
端口已经备用了？

**Comment by zhako022** [comment]
不清楚 有可能是  也有可能没有吧
那怎样解决？求解決
我是mu连接ss-panel前端
其实是BUG还是什么问题?
我用另一台ss服务端 再安装mu 连接ss-panel前端 还是提示端口被占用

**Comment by orvice** [comment]
./mu -debug
这样跑下，发log

**Comment by zhako022** [comment]
./mu -debug  就是出现大量用户数据
[37mDEBU[0m[0002] check user for 1111  
[34mINFO[0m[0002] new user to run{1 1111 xxxxxx rc4-md5 1 148458232320 227808707 1383721850} 
[31mERRO[0m[0002] error listening port 1111: listen tcp :1111: bind: address already in use
log大约是出现这些   有大量这些数据

**Comment by orvice** [comment]
redis库里有数据么？

**Comment by zhako022** [comment]
redis库是指?
是不是以下?   有大量用户数据
http://my url/mu/users?key=xxxxx

**Comment by orvice** [comment]
redis-cli
select 1
keys *

**Comment by zhako022** [comment]
205) "userinfo:1257"
206) "userinfo:1219"
207) "userinfo:1113"
208) "userinfo:1439"
209) "userinfo:1087"
210) "userinfo:1056"
211) "userinfo:1069"
212) "userinfo:1468"
213) "userinfo:1245"
214) "userinfo:1455"
215) "userinfo:1254"
216) "userinfo:2099"
217) "userinfo:1381"
218) "userinfo:1357"
219) "userinfo:2104"
220) "userinfo:1283"
221) "userinfo:1070"
222) "userinfo:2100"
223) "userinfo:1231"
224) "userinfo:1112"

**Comment by zhako022** [comment]
每次启动./mu都提示不同的端被占用 导致mu自动退出
ss go mu和sspanel我是安装在不同的vps上 可以吧?
