### ISSUE TITLE
go mu版无法正常启动

### ISSUE THREAD

**Issue by hpfs0** [orvice/shadowsocks-go#30]
root@50KVM-2016316749:~/.go/bin# ./mu -debug
DEBU[0000] debug on  
INFO[0000] PONG  
ERRO[0000] Get User Errorinvalid character '<' looking for beginning of value

**Comment by orvice** [comment]
访问 /mu/users?key=**
是否正常？

**Comment by hpfs0** [comment]
已解决，webapi的url里忘写/mu了。谢谢！
