### ISSUE TITLE
webapi方式出现错误“ERR wrong number of arguments for 'set' command”

### ISSUE THREAD

**Issue by yueker** [orvice/shadowsocks-go#31]
INFO[0064] [port-10020]connecting 74.125.25.188:5228
DEBU[0064] 10020 conn debug:  local addr: 192.157.226.60:10020 | remote addr: 114.250.57.42:34494 network: tcp
ERRO[0064] ERR wrong number of arguments for 'set' command
ERRO[0064] [port-10020]  Error: request 74.125.25.188:5228 cancel
DEBU[0065] new client 114.250.57.42:47170->192.157.226.60:10020

**Comment by orvice** [comment]
redis版本？

**Comment by yueker** [comment]
Redis server version 2.4.14 (00000000:0)

**Comment by orvice** [comment]
你的redis版本太老了

> The extra options to SET have been supported since Redis 2.6.12. Likely you're running an older version of Redis.

要求2.6.12+

via https://github.com/redis/redis-rb/issues/372

**Comment by yueker** [comment]
多谢
