### ISSUE TITLE
go版本ss连接正常，但是会有以下Error，是不是不支持UDP？

### ISSUE THREAD

**Issue by yueker** [orvice/shadowsocks-go#33]
9.59.148.73:443 cancel"
time="2016-03-31T10:16:20+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:17:40+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:17:58+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:17:58+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:18:01+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:18:03+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:18:03+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:18:06+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:18:20+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:18:20+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:18:22+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:18:23+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:18:25+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:18:28+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:18:30+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:19:11+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:22:12+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:22:12+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:22:17+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:22:22+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:22:25+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:22:25+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:22:30+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:22:35+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:26:42+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:26:43+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:26:43+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:27:05+08:00" level=error msg="[port-10020]  Error: request 8.8.8.8:53 cancel"
time="2016-03-31T10:27:06+08:00" level=error msg="[port-10020]  Error: request 216.58.216.42:443 cancel"

**Comment by orvice** [comment]
对，不支持udp
