### ISSUE TITLE
go mu如何指定配置文件路径？

### ISSUE THREAD

**Issue by HuanMeng0** [orvice/shadowsocks-go#36]
用supervisor运行mu版，但是出现了错误，错误如下：
ERRO[0000] open config.conf: no such file or directory

**Comment by orvice** [comment]
```
[program:ss]
directory=/home/ss
command=/home/ss/mu
autorestart=true
user=user
```

供参考。

**Comment by HuanMeng0** [comment]
还有个问题，
我执行 supervisorctl start ss，会出错，Google过找不到解决办法……

> [root@localhost supervisor]# supervisorctl start ss
> ss: ERROR (spawn error)

**Comment by HuanMeng0** [comment]
VPS是搬瓦工
