### ISSUE TITLE
webapi错误：Get User Errorinvalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by yylzcom** [orvice/shadowsocks-go#38]
webapi方式自己大概配置了一下，出现上述提示，请问是哪儿的问题；

另外，用mysql方式配置成功后看ss.log都有成功更新流量和同步的提示，但是数据库中并没有相应的数据写入，而且面板中也看不到节点在线详情，已使用流量一直都是0

**Comment by lion1991** [comment]
把你的url地址后面加上  /mu

**Comment by yylzcom** [comment]
感谢，webapi的问题已经解决
