### ISSUE TITLE
关于 shawdowsocks-go 和 mu 的问题

### ISSUE THREAD

**Issue by Yunlong2cn** [orvice/shadowsocks-go#41]
```
[root@60bcb29b98fb mu]# mu
INFO[0000] PONG
INFO[0000] 1
INFO[0000] 1
INFO[0000] 1
INFO[0000] new user to run{1 8389 ZD05pf rc4-md5 1 5467275264 0 0}
INFO[0000] check finish...
INFO[0000] server listening port 8389 ...

INFO[0000] 1
INFO[0000] sync finish...start logging online count
```

mu 已经跑起来了 ，但是客户端配置后仍然无法联网，是否需要单独跑 shadowsocks-server ?

接着，我又重新 go get 了一下 shadowsocks-server ，并且，shadowsocks-server 正常执行

```
[root@60bcb29b98fb bin]# ./shadowsocks-server
2016/04/13 09:40:55 server listening port 8388 ...
2016/04/13 09:41:02 creating cipher for port: 8388
2016/04/13 09:41:02 error getting request 60.208.166.115:61586 192.168.0.9:8388 addr type 117 not supported

``

这时候，如果我在客户端直接使用 shadowsocks-server 中 config.json 密码和 method 则可以正常连网，但是如果我使用 mu 中生成的密码和 method 则无法联网，请问这个要怎么解决？
```

**Comment by orvice** [comment]
是用这个信息去连接的么

```
8389 ZD05pf rc4-md5
```

**Comment by imoldchen** [comment]
同样的问题，安装过程没问题，启动没有问题，连接信息也对，就是连不上。CentOS7 64bit
和 ss-panel3 搭配使用的 webapi 模式

**Comment by lion1991** [comment]
尝试修改iptables规则,或者关闭iptables?

**Comment by rogerlan** [comment]
同样的问题,查看了一下:
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
mu      4070 root    9u  IPv6  14976      0t0  TCP *:1026 (LISTEN)

似乎只监听IPV6端口？

netstat -anp | grep 1026
tcp6       0      0 :::1026                 :::\*                    LISTEN      4070/mu

**Comment by rogerlan** [comment]
如有需要，我这儿可以提供该问题环境的SSH权限。

**Comment by orvice** [comment]
系统是centos？

`iptables -L`

执行下这个

**Comment by rogerlan** [comment]
系统是ubuntu 15.10 64位 

root@:~# iptables -L
Chain INPUT (policy DROP)
target     prot opt source               destination  
f2b-sshd   tcp  --  anywhere             anywhere             multiport dports ssh
fail2ban-VESTA  tcp  --  anywhere             anywhere             tcp dpt:8083
fail2ban-SSH  tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     tcp  --  0.0.0.0              anywhere             multiport dports 1025:1225
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     tcp  --  anywhere             anywhere             multiport dports http,https
ACCEPT     tcp  --  anywhere             anywhere             multiport dports ftp,12000:12100
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             multiport dports smtp,urd,submission,2525
ACCEPT     tcp  --  anywhere             anywhere             multiport dports pop3,pop3s
ACCEPT     tcp  --  anywhere             anywhere             multiport dports imap2,imaps
ACCEPT     tcp  --  anywhere             anywhere             multiport dports mysql,postgresql
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8083
ACCEPT     icmp --  anywhere             anywhere            

ACCEPT     all  --  localhost            anywhere  
ACCEPT     tcp  --  anywhere             anywhere             tcp spt:ftp-data
ACCEPT     tcp  --  anywhere             anywhere             tcp spt:ftp
ACCEPT     tcp  --  anywhere             anywhere             tcp spt:ssh
ACCEPT     tcp  --  anywhere             anywhere             tcp spt:smtp
ACCEPT     udp  --  anywhere             anywhere             udp spt:domain
ACCEPT     tcp  --  anywhere             anywhere             tcp spt:http
ACCEPT     tcp  --  anywhere             anywhere             tcp spt:https
ACCEPT     tcp  --  anywhere             anywhere             tcp spt:pop3
ACCEPT     udp  --  anywhere             anywhere             udp spt:ntp
ACCEPT     tcp  --  anywhere             anywhere             tcp spt:imap2
ACCEPT     tcp  --  anywhere             anywhere             tcp spt:mysql
ACCEPT     tcp  --  anywhere             anywhere             tcp spt:postgresql
ACCEPT     tcp  --  anywhere             anywhere             tcp spt:http-alt
ACCEPT     tcp  --  anywhere             anywhere             tcp spt:8433
ACCEPT     tcp  --  anywhere             anywhere             tcp spt:8083
ACCEPT     tcp  --  anywhere             anywhere             tcp spts:12000:12100
ACCEPT     tcp  --  anywhere             anywhere             state RELATED,ESTABLISHED

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain f2b-sshd (1 references)
target     prot opt source               destination  
REJECT     all  --  58.218.204.215       anywhere             reject-with icmp-port-unreachable
RETURN     all  --  anywhere             anywhere  
RETURN     all  --  anywhere             anywhere            

Chain fail2ban-SSH (1 references)
target     prot opt source               destination  
REJECT     all  --  58.218.204.215       anywhere             reject-with icmp-port-unreachable
RETURN     all  --  anywhere             anywhere            

Chain fail2ban-VESTA (1 references)
target     prot opt source               destination  
RETURN     all  --  anywhere             anywhere            

Chain vesta (0 references)
target     prot opt source               destination

**Comment by Yunlong2cn** [comment]
我重新装了一下就好了，什么额外的操作也没有弄，先结束了

**Comment by rogerlan** [comment]
难道。。我也需要重装？这不科学啊！orvice大神帮忙！
