### ISSUE TITLE
出现ERR wrong number of arguments for 'set' command的错误信息

### ISSUE THREAD

**Issue by XOXoNone** [orvice/shadowsocks-go#42]
在正常使用大概一周的时间以后突然出现了这样的出错信息
`INFO[0010] [port-30000]connecting global.bing.com:80    
ERRO[0010] ERR wrong number of arguments for 'set' command 
INFO[0060] 18                                           
INFO[0060] 18                                           
INFO[0060] check finish...                              
INFO[0060] sync finish...start logging online count`
重启vps和radis服务端都无法解决...请问是什么问题

**Comment by orvice** [comment]
redus版本多少

**Comment by XOXoNone** [comment]
你好...
`[root@NoneIDCF-2 ~]# redis-server --version
Redis server version 2.4.10 (00000000:0)
`

**Comment by orvice** [comment]
升级下版本吧
https://github.com/redis/redis-rb/issues/372

**Comment by XOXoNone** [comment]
谢谢 更新到3.0.7正常了...但是很不解,我另外一台vps上的redis的版本也是2.4.10,和这台一样已经用了很久了都没出问题
