### ISSUE TITLE
两台vps同时访问http://ip/mu/users?key=xxx其中一台返回正常，一台返回{"ret":0,"msg":"source is invalid"}

### ISSUE THREAD

**Issue by yueker** [orvice/shadowsocks-go#45]
两台vps同时访问http://ip/mu/users?key=xxx其中一台返回正常，一台返回{"ret":0,"msg":"source is invalid"}

**Comment by orvice** [comment]
mu的完整log发下

**Comment by yueker** [comment]
这个吗？
DEBU[0000] debug on
INFO[0000] PONG
DEBU[0000] {"ret":0,"msg":"source is  invalid"}
INFO[0000] 0
INFO[0000] 0
DEBU[0000] {"ret":0,"msg":"source is  invalid"}
INFO[0000] 0
DEBU[0000] []
INFO[0000] check finish...
DEBU[0000] {"ret":0,"msg":"source is  invalid"}
INFO[0000] 0
INFO[0000] sync finish...start logging online count
ERRO[0000] Update Online Count Failed
ERRO[0000] Update Online Count Failed

**Comment by orvice** [comment]
ss-panel是不是最新版

**Comment by yueker** [comment]
我用的是个修改版，跟ss-panel有关？

**Comment by yueker** [comment]
重新建立了一下数据库好了

**Comment by winer632** [comment]
请问重新建立哪个数据库？

我也遇到这个问题了，我的config.conf中关于mysql的配置是这样的，有问题吗？

[mysql]
host  127.0.0.1:3306
user root
pass sOHSS_)@@)#R_382984
db  sspanel
table user

[root@localhost bin]# supervisorctl tail -f shadowsocks stderr
==> Press Ctrl-C to exit <==
time="2016-06-13T08:48:29-04:00" level=info msg=PONG
time="2016-06-13T08:48:30-04:00" level=info msg=0
time="2016-06-13T08:48:30-04:00" level=info msg=0
time="2016-06-13T08:48:30-04:00" level=info msg=0
time="2016-06-13T08:48:30-04:00" level=info msg="check finish..."
time="2016-06-13T08:48:30-04:00" level=info msg=0
time="2016-06-13T08:48:30-04:00" level=info msg="sync finish...start logging online count"
time="2016-06-13T08:48:30-04:00" level=error msg="Update Online Count Failed"
time="2016-06-13T08:48:30-04:00" level=error msg="Update Online Count Failed"
time="2016-06-13T08:49:30-04:00" level=info msg=0
time="2016-06-13T08:49:30-04:00" level=info msg="check finish..."
time="2016-06-13T08:49:30-04:00" level=info msg=0
time="2016-06-13T08:49:30-04:00" level=info msg="sync finish...start logging online count"
time="2016-06-13T08:49:30-04:00" level=error msg="Update Online Count Failed"
time="2016-06-13T08:49:30-04:00" level=error msg="Update Online Count Failed"
^C
[root@localhost bin]#
