### ISSUE TITLE
有时会出现某一个端口的用户无法连接，log里无任何显示，确认网络无问题

### ISSUE THREAD

**Issue by echoowall** [orvice/shadowsocks-go#49]
修改了连接密码（或其他信息比如加密方式）以后就连接正常，请问是什么原因？

**Comment by zuoruizhi** [comment]
netstat -lanp |grep 端口
看下端口开没开  
PC上可以telnet IP 端口

**Comment by echoowall** [comment]
开了的，是一开始可以连接，但是突然就不行了，改一下加密方式或者连接密码以后又可以了

**Comment by zuoruizhi** [comment]
突然就不行了的时候端口正常吗
