### ISSUE TITLE
运行shaodwsocks-go时提示Update Online Count Failed，是什么问题。

### ISSUE THREAD

**Issue by ghost** [orvice/shadowsocks-go#51]
已经将ss-panel用的sql文件导进数据库
运行时提示
INFO[0000] PONG
INFO[0000] 0
INFO[0000] 0
INFO[0000] 0
INFO[0000] sync finish...start logging online count
INFO[0000] 0
INFO[0000] check finish...
ERRO[0000] Update Online Count Failed
ERRO[0000] Update Online Count Failed

**Comment by HenryQW** [comment]
咋解决的？

**Comment by winer632** [comment]
同问，咋解决的？
