### ISSUE TITLE
请问多用户的服务端都需要数据库的哪些权限

### ISSUE THREAD

**Issue by blueyi** [orvice/shadowsocks-go#61]
要知道shadowsocks-go mu的服务端都需要数据库的哪些权限，不想给节点太多数据库的访问权限，最好能限制到字段级，例如用户邮箱应该肯定是不需要的吧，谢谢

**Comment by MoeGakuen** [comment]
你使用WebAPI不就好了吗，就不用烦权限了

**Comment by orvice** [comment]
用api去访问，不需要数据库权限。

**Comment by blueyi** [comment]
@orvice 意思是说设置了webapi之后就可以不设置数据库了吗？是否有相关文档？谢谢
