### ISSUE TITLE
流量统计到2G之后就不再更新了，有时甚至会减少。 比如我手动把user表里面的d字段改为3G，然后重启shadowsocks-go,流量自动变成2G

### ISSUE THREAD

**Issue by winer632** [orvice/shadowsocks-go#67]
流量统计到2G之后就不再更新了，有时甚至会减少。
比如我手动把user表里面的d字段改为3G，然后重启shadowsocks-go，流量自动变成2G。

**Comment by kamingchan** [comment]
@winer632 请使用 64 位系统，32 位整形类型表示字节，最大就是 2G 左右。 [参考](https://github.com/orvice/ss-panel/issues/456)
