### ISSUE TITLE
Releases v2.1 go get时遇到如下错误 cannot use v (type *User) as type

### ISSUE THREAD

**Issue by kalonelee** [orvice/shadowsocks-go#71]
`#` github.com/orvice/shadowsocks-go/mu/mysql
../../../orvice/shadowsocks-go/mu/mysql/mysql.go:117: cannot use v (type _User) as type "shadowsocks/shadowsocks-go/mu/user".User in assignment:
    *User does not implement "shadowsocks/shadowsocks-go/mu/user".User (wrong type for GetCipher method)
        have GetCipher() (_"shadowsocks/shadowsocks-go/shadowsocks".Cipher, error, bool)
        want GetCipher() (_"github.com/shadowsocks/shadowsocks-go/shadowsocks".Cipher, error)
`#` github.com/orvice/shadowsocks-go/mu/webapi
../../../orvice/shadowsocks-go/mu/webapi/web.go:66: cannot use v (type User) as type "shadowsocks/shadowsocks-go/mu/user".User in assignment:
    User does not implement "shadowsocks/shadowsocks-go/mu/user".User (wrong type for GetCipher method)
        have GetCipher() (_"shadowsocks/shadowsocks-go/shadowsocks".Cipher, error, bool)
        want GetCipher() (*"github.com/shadowsocks/shadowsocks-go/shadowsocks".Cipher, error)

go version go1.6.3 linux/amd64

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/.go"
GORACE=""
GOROOT="/root/.gvm/gos/go1.6.3"
GOTOOLDIR="/root/.gvm/gos/go1.6.3/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

请问下应该怎么解决？

**Comment by ghost** [comment]
我也遇到了同样的错误
