### ISSUE TITLE
 unrecognized import path "shadowsocks/shadowsocks-go/mu/config" (import path does not begin with hostname)

### ISSUE THREAD

**Issue by winer632** [orvice/shadowsocks-go#72]
请问下面的操作哪里不对？

[root@iZ23wdokwemZ home]# tar -C /usr/local/ -xzf go1.6.3.linux-amd64.tar.gz 
[root@iZ23wdokwemZ home]# export PATH=$PATH:/usr/local/go/bin
[root@iZ23wdokwemZ home]# export GOPATH=~/.go
[root@iZ23wdokwemZ home]# go get github.com/orvice/shadowsocks-go 
package github.com/orvice/shadowsocks-go: no buildable Go source files in /root/.go/src/github.com/orvice/shadowsocks-go
[root@iZ23wdokwemZ home]# 
[root@iZ23wdokwemZ home]# cd ~/.go/src/github.com/orvice/shadowsocks-go/mu
[root@iZ23wdokwemZ mu]# 
[root@iZ23wdokwemZ mu]# go get
package shadowsocks/shadowsocks-go/mu/config: unrecognized import path "shadowsocks/shadowsocks-go/mu/config" (import path does not begin with hostname)
package shadowsocks/shadowsocks-go/mu/log: unrecognized import path "shadowsocks/shadowsocks-go/mu/log" (import path does not begin with hostname)
package shadowsocks/shadowsocks-go/mu/mysql: unrecognized import path "shadowsocks/shadowsocks-go/mu/mysql" (import path does not begin with hostname)
package shadowsocks/shadowsocks-go/mu/user: unrecognized import path "shadowsocks/shadowsocks-go/mu/user" (import path does not begin with hostname)
package shadowsocks/shadowsocks-go/mu/webapi: unrecognized import path "shadowsocks/shadowsocks-go/mu/webapi" (import path does not begin with hostname)
package shadowsocks/shadowsocks-go/shadowsocks: unrecognized import path "shadowsocks/shadowsocks-go/shadowsocks" (import path does not begin with hostname)
[root@iZ23wdokwemZ mu]# 
[root@iZ23wdokwemZ mu]# goenv
-bash: goenv: command not found
[root@iZ23wdokwemZ mu]# go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/.go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build414297166=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
[root@iZ23wdokwemZ mu]# 
[root@iZ23wdokwemZ mu]# go version
go version go1.7rc6 linux/amd64
[root@iZ23wdokwemZ mu]#

**Comment by foonsun** [comment]
和楼主同样的安装问题。求解答！

**Comment by orvice** [comment]
在这里下最新二进制包
http://down.moe.gr/ss-go-mu/v2.0/
