### ISSUE TITLE
unrecognized import path "shadowsocks/shadowsocks-go/mu/config" (import path does not begin with hostname)

### ISSUE THREAD

**Issue by a3318375** [orvice/shadowsocks-go#73]
[root@vultr mu]# go get
package shadowsocks/shadowsocks-go/mu/config: unrecognized import path "shadowsocks/shadowsocks-go/mu/config" (import path does not begin with hostname)
package shadowsocks/shadowsocks-go/mu/log: unrecognized import path "shadowsocks/shadowsocks-go/mu/log" (import path does not begin with hostname)
package shadowsocks/shadowsocks-go/mu/mysql: unrecognized import path "shadowsocks/shadowsocks-go/mu/mysql" (import path does not begin with hostname)
package shadowsocks/shadowsocks-go/mu/user: unrecognized import path "shadowsocks/shadowsocks-go/mu/user" (import path does not begin with hostname)
package shadowsocks/shadowsocks-go/mu/webapi: unrecognized import path "shadowsocks/shadowsocks-go/mu/webapi" (import path does not begin with hostname)
package shadowsocks/shadowsocks-go/shadowsocks: unrecognized import path "shadowsocks/shadowsocks-go/shadowsocks" (import path does not begin with hostname)
[root@vultr mu]# 
求助啊

**Comment by orvice** [comment]
在这里下载最新编译好的二进制文件
http://down.moe.gr/ss-go-mu/v2.0/
