### ISSUE TITLE
在新服务器，新编译出来的mu用不了；把老服务器编译好的mu复制过来就可以用

### ISSUE THREAD

**Issue by choicky** [orvice/shadowsocks-go#78]
我的ss-panel 在A服务器，老mu在B服务器。

最近搞了个C服务器，硬件与软件环境与B一样。

用相同的方法，在C服务器编译出来的mu在运行 mu -debug 时，显示能连上ss-panel，但很快就没有输出了。此时发现C服务器的ss无法使用。go1.6.x 和 go1.7都尝试过。

如把B服务器的mu复制到C服务器，就能正常使用。

B服务器大概是六七月份编译的。即，使用的mu源码很可能是相同的。

**Comment by ghost** [comment]
master 分支最新代码编译确实有 BUG，作者太懒已经半个月没管了，提的 Issues 基本不回，`git reset --hard f8efa67d51b887f8e10f351ba7d3fa8e0c327fcc` 回退到 `
support docker image build` 版本可正常编译使用

**Comment by choicky** [comment]
@zoakerc Thank you very much.
也希望 @orvice 能抽空 fiix 下代码

**Comment by orvice** [comment]
最新版已经更新。
