### ISSUE TITLE
mu版无法初始化用户端口问题（已屏蔽）

### ISSUE THREAD

**Issue by WeyNiDrop** [orvice/shadowsocks-go#79]
问题描述：初始化的时候端口没有被绑定却依然反回了绑定
期待 @orvice 把这个问题kill掉，我只是做了简单的跳过
解决方法在博客里http://blog.csdn.net/w2180z/article/details/52402413

**Comment by ghost** [comment]
@wz812180 看了博客，为什么博主不 PR 一发呢？

**Comment by WeyNiDrop** [comment]
@zoakerc PR？什么意思

**Comment by ghost** [comment]
fork 修改后可以 pull request

**Comment by WeyNiDrop** [comment]
@zoakerc 我只是绕过了这个错误，并没有把错误key掉，还是需要等作者排除问题
