### ISSUE TITLE
关于UDP和FASTOPEN

### ISSUE THREAD

**Issue by ghost** [orvice/shadowsocks-go#83]
关于[UDP](https://github.com/shadowsocks/shadowsocks-go/pull/72)和[FAST_OPEN](https://github.com/shadowsocks/shadowsocks-go/pull/101)，官方版貌似已经合并支持的分支了，我只是路过，作者可以参考。

**Comment by seanchann** [comment]
https://github.com/bjjyd/shadowsocks-go support for udp.
FAST_OPEN in todo list
