### ISSUE TITLE
shadowsocks go mu can't starting, Get User Error%!(EXTRA *json.Unmarshal was reported

### ISSUE THREAD

**Issue by ghost** [orvice/shadowsocks-go#87]
When I starting the shadowsocks go mu, the following messages are output:
time="2017-06-23T17:44:52+08:00" level=info msg=PONG
E0623 17:44:53.025237    9731 boot.go:36] Get User Error%!(EXTRA *json.UnmarshalTypeError=json: cannot unmarshal number 1.073741824021e+18 into Go struct field User.transfer_enable of type int64)

Should I to do?
Thanks!

**Comment by orvice** [comment]
please check new version
https://github.com/catpie/ss-go-mu
